### ISSUE TITLE
home-assistant:stable points at older release

### ISSUE THREAD

**Issue by tribut** [home-assistant/hassio-homeassistant#59] opened 2019-09-23 12:03 UTC
Currently, `homeassistant/home-assistant:stable` points to 0.99.1, even though 0.99.2 was released three days ago and a docker image for it exists.

Cf. https://github.com/home-assistant/home-assistant-polymer/issues/3795

**Comment by frenck** [comment] 2019-09-23 12:04
Duplicate of home-assistant/home-assistant#26764

**Closed by frenck** 2019-09-23 12:04 UTC
